Vagrant.configure("2") do |config|
    config.vm.box = "peru/ubuntu-20.04-server-amd64"
    config.vm.hostname = "storm"
    config.vm.box_check_update = false

    config.vm.network "private_network", ip: "192.168.33.3"

    config.vm.provider "virtualbox" do |v|
        v.gui = false
        v.memory = "1024"
        v.cpus = 1
    end
end
