export enum ERROR_MESSAGE {
    INVALID_TOKEN = 'ERROR/INVALID_TOKEN',
    INVALID_VERIFICATION_CODE = 'ERROR/INVALID_VERIFICATION_CODE',
    MISSING_AUTHENTICATION_TOKEN = 'ERROR/MISSING_AUTHENTICATION_TOKEN',
    UNAUTHORIZED_ACTION = 'ERROR/UNAUTHORIZED_ACTION',
    SERVER_ERROR = 'ERROR/SERVER_ERROR',
    BAD_REQUEST_ERROR = 'ERROR/BAD_REQUEST_ERROR',
    REQUEST_CLIENT_NOT_FOUND = 'ERROR/REQUEST_CLIENT_NOT_FOUND',
    HTTP_EXCEPTION = 'ERROR/HTTP_EXCEPTION',

    AUTH_PROVIDER_ERROR = 'ERROR/AUTH_PROVIDER_ERROR',
    DELETE_IMAGE_ERROR = 'ERROR/DELETE_IMAGE_ERROR',
    UPLOAD_IMAGE_ERROR = 'ERROR/UPLOAD_IMAGE_ERROR',
    SECRET_ERROR = 'ERROR/SECRET_ERROR',
}
