export enum SECRETS {
    FIREBASE_CREDENTIALS = 'FIREBASE_CREDENTIALS',
    FIREBASE_DATABASE_URL = 'FIREBASE_DATABASE_URL',
    FIREBASE_WEB_KEY = 'FIREBASE_WEB_KEY',
    MEILISEARCH_MASTER_KEY = 'MEILISEARCH_MASTER_KEY',
}
